import { Inter } from "next/font/google";
import "./globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Investor5",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(); // Fetch session on the server

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <SessionProviderWrapper >{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
