import SessionProviderWrapper from "@/app/SessionProviderWrapper";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Investor5",
  description: "Generated by create next app",
};

export default async function AdminDashboardLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body className={inter.className} suppressHydrationWarning>
        <SessionProviderWrapper suppressHydrationWarning>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
